include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: false  # Allow prints in example app for demonstration
    - prefer_const_constructors: true
    - prefer_const_literals_to_create_immutables: true
    - prefer_const_constructors_in_immutables: true

