name: pusher_reverb_flutter
description: "A Flutter Pusher client for Laravel Reverb, with support for custom WebSocket paths and dynamic authentication headers. Aims to be a reliable and feature-rich alternative."
version: 0.0.1
repository: https://github.com/shadatrahman/pusher_reverb_flutter

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  meta: ^1.12.0
  http: ^1.1.0
  
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.10
  async: ^2.11.0
  stream_channel: ^2.1.2

flutter: {}
